<a href="https://colab.research.google.com/github/chuangchai49097/data_viz_2022/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# เตรียมข้อมูล

In [ ]:
import pandas as pd # import ฟังก์ชัน pandas

In [ ]:
from google.colab import drive # เชื่อม drive ของเรา ถ้าเชื่อมสำเร็จจะขึ้นคำว่าMounted at /content/drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os # จัดการเกี่ยวกับไฟล์ต่างๆ ในโฟล์เดอร์

In [ ]:
path = '/content/drive/My Drive/dataviz_2021_data' # ชี้ว่า data เราอยู่โฟล์เดอร์ไหน

In [ ]:
data_file_path = os.path.join(path,'alldb.csv') # เอาที่อยู่ของไฟล์เชื่อมกับที่อยู่ของไฟล์เรา โดยกำหนดชื่่อไฟล์ที่เราต้องการ
data_alldb = pd.read_csv(data_file_path)

In [ ]:
data_alldb

,Unnamed: 0,user,RowKey,care,date,ov,phone,site,time,urine,pid,PartitionKey,title,age
0,0,test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
1,1,04857,136FD222-FD9F-4E54-AE1F-7282A276B085,NaN,2022-02-24,NaN,"iPhone10,4",05310,10:50:32,NaN,NaN,NaN,data is not completed,data is not completed
2,2,NaN,1E6D3D62-4C8A-4F8E-90D1-0DC5BC2752DF.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
3,3,3450101576642,2D331FB0-CBA2-4586-A5B0-CB3CF44DD9FE,NaN,2022-02-23,0,"iPhone13,4",05087,09:59:47,ปกติ (เหลืองใส),NaN,NaN,data is not completed,data is not completed
4,4,3450101576642,45197AF7-7CB4-470C-9ABB-37C092BD6B21,NaN,2022-02-23,NaN,"iPhone13,4",05087,09:44:06,ปกติ (เหลืองใส),NaN,NaN,data is not completed,data is not completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40030,40030,NaN,6B5FA20F-190E-4021-8547-C12308024C6C,NaN,NaN,NaN,"iPhone13,4",01234,NaN,NaN,5,เกษศิรินทร์ ไชยลาภ,data is not completed,data is not completed
40031,40031,NaN,F48C51C0-A345-40D6-93F4-46213267E1B1,NaN,NaN,2,"iPhone10,5",01234,NaN,ปกติ (เหลืองใส),5,เถลิงเกียรติ เสริฐเลิศ,data is not completed,data is not completed
40032,40032,NaN,A986BDAA-6D7C-4017-8E62-A3C104E946B9,NaN,NaN,1,"iPhone13,4",01234,NaN,ปกติ (เหลืองใส),1,เสรี,data is not completed,data is not completed
40033,40033,NaN,bbuogxulur.png,NaN,NaN,NaN,Samsung SM-A115F,01234,NaN,NaN,1,เสรี,data is not completed,data is not completed
40034,40034,NaN,zttpqogiso.png,NaN,NaN,1,Samsung SM-A115F,01234,NaN,ปกติ (เหลืองใส),1,เสรี,data is not completed,data is not completed

In [ ]:
data_file_path2 = os.path.join(path,'hospital_list.xlsx')
data_hospital = pd.read_excel(data_file_path2)

In [ ]:
data_hospital

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,00001,สำนักงานสาธารณสุขจังหวัดสมุทรปราการ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,1.0,ปากน้ำ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,สป,SPK
1,00002,สำนักงานสาธารณสุขจังหวัดนนทบุรี,4,สาขาพื้นที่(สระบุรี),12.0,นนทบุรี,1.0,เมืองนนทบุรี,4.0,บางกระสอ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,นบ,NBI
2,00003,สำนักงานสาธารณสุขจังหวัดปทุมธานี,4,สาขาพื้นที่(สระบุรี),13.0,ปทุมธานี,1.0,เมืองปทุมธานี,1.0,บางปรอก,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,ปท,PTE
3,00004,สำนักงานสาธารณสุขจังหวัดพระนครศรีอยุธยา,4,สาขาพื้นที่(สระบุรี),14.0,พระนครศรีอยุธยา,1.0,พระนครศรีอยุธยา,3.0,หอรัตนไชย,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,อย,AYA
4,00005,สำนักงานสาธารณสุขจังหวัดอ่างทอง,4,สาขาพื้นที่(สระบุรี),15.0,อ่างทอง,1.0,เมืองอ่างทอง,8.0,บ้านอิฐ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,อท,ATG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,อต,UTT
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ปข,PKN
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ศก,SSK
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR

# จัดการข้อมูล

In [ ]:
new_alldb = data_alldb[['user','RowKey','date','phone','site','time','urine','ov','PartitionKey']] # ตัดให้เหลือ column ที่ต้องการนำไปใช้
new_alldb

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
0,test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04857,136FD222-FD9F-4E54-AE1F-7282A276B085,2022-02-24,"iPhone10,4",05310,10:50:32,NaN,NaN,NaN
2,NaN,1E6D3D62-4C8A-4F8E-90D1-0DC5BC2752DF.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3450101576642,2D331FB0-CBA2-4586-A5B0-CB3CF44DD9FE,2022-02-23,"iPhone13,4",05087,09:59:47,ปกติ (เหลืองใส),0,NaN
4,3450101576642,45197AF7-7CB4-470C-9ABB-37C092BD6B21,2022-02-23,"iPhone13,4",05087,09:44:06,ปกติ (เหลืองใส),NaN,NaN
...,...,...,...,...,...,...,...,...,...
40030,NaN,6B5FA20F-190E-4021-8547-C12308024C6C,NaN,"iPhone13,4",01234,NaN,NaN,NaN,เกษศิรินทร์ ไชยลาภ
40031,NaN,F48C51C0-A345-40D6-93F4-46213267E1B1,NaN,"iPhone10,5",01234,NaN,ปกติ (เหลืองใส),2,เถลิงเกียรติ เสริฐเลิศ
40032,NaN,A986BDAA-6D7C-4017-8E62-A3C104E946B9,NaN,"iPhone13,4",01234,NaN,ปกติ (เหลืองใส),1,เสรี
40033,NaN,bbuogxulur.png,NaN,Samsung SM-A115F,01234,NaN,NaN,NaN,เสรี
40034,NaN,zttpqogiso.png,NaN,Samsung SM-A115F,01234,NaN,ปกติ (เหลืองใส),1,เสรี

In [ ]:
new_alldb.isnull().sum() # เช็คค่า missing

user            762
RowKey            1
date            554
phone             3
site             99
time            557
urine           253
ov              364
PartitionKey    185
dtype: int64

In [ ]:
drop_alldb = new_alldb.dropna() # จัดการค่า missing โดยการ drop ทิ้งไป
drop_alldb

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13:08:39,มีตะกอน,0,0000
186,45-161,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",04312,09:45:28,ปกติ (เหลืองใส),0,0-1528
187,45-161,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",04312,10:06:45,ปกติ (เหลืองใส),0,0-1544
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000
190,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,00000
...,...,...,...,...,...,...,...,...,...
40013,ttest,crqcufokmn.png,2022-02-21,Samsung SM-G998B,test,14:23:45,ขุ่น,2,x001
40014,ttest,gzxgflnowr.png,2022-02-21,Samsung SM-G998B,test,14:23:43,ขุ่น,2,x001
40016,xxx,jytlopevha.png,2022-02-17,Samsung SM-N950F,xxx,00:01:06,ปกติ (เหลืองใส),3,xxx
40022,yyy,ivccsksowb.png,2022-02-17,Samsung SM-N950F,yyy,08:41:05,มีเม็ดเลือดแดง,2,yyy
40023,zzz,psudrnccsh.png,2022-02-17,Samsung SM-N950F,zzz,08:41:04,มีตะกอน,2,zzz

In [ ]:
# เช็คข้อมูลหลังจากการ drop ว่าหายไปกี่เปอร์เซ็นต์
removes = new_alldb.shape[0] - drop_alldb.shape[0]
print(f'size before drop = {new_alldb.shape[0]}')
print(f'size after drop = {drop_alldb.shape[0]}')
print(f'% from drop = {(removes/new_alldb.shape[0])*100}')

size before drop = 40035
size after drop = 38663
% from drop = 3.427001373797927

## จัดการให้ค่า site เป็นตัวเลข 5 หลัก(ตัวเลขเท่านั้น)

In [ ]:
set(drop_alldb['site']) # set ดูค่าที่เก็บไว้

{' 0502',
 '00004',
 '00006',
 '00007',
 '00008',
 '00012',
 '00016',
 '00017',
 '00018',
 '00027',
 '00028',
 '00040',
 '00052',
 '00055',
 '00061',
 '00069',
 '00070',
 '00071',
 '00081',
 '00082',
 '00090',
 '00094',
 '00096',
 '00108',
 '00109',
 '00115',
 '00120',
 '00122',
 '00127',
 '00163',
 '00164',
 '00165',
 '00166',
 '00169',
 '00170',
 '00171',
 '00173',
 '00174',
 '00176',
 '00177',
 '00178',
 '00179',
 '00180',
 '00182',
 '00185',
 '00186',
 '00187',
 '00189',
 '00190',
 '00191',
 '00192',
 '00193',
 '00194',
 '00195',
 '00196',
 '00197',
 '00198',
 '00200',
 '00202',
 '00204',
 '00205',
 '00206',
 '00207',
 '00209',
 '00213',
 '00214',
 '00217',
 '00218',
 '00219',
 '00229',
 '00232',
 '00235',
 '00240',
 '00247',
 '00266',
 '00271',
 '00279',
 '00323',
 '00331',
 '00333',
 '00346',
 '00348',
 '00381',
 '00382',
 '00385',
 '00387',
 '00388',
 '00389',
 '00390',
 '00391',
 '00394',
 '00397',
 '00400',
 '00401',
 '00404',
 '00406',
 '00408',
 '00410',
 '00411',
 '00412',
 '00413',
 '00414',
 '00415',
 '00512',
 '00513',
 '00579',
 '00580',
 '00956',
 '01151',
 '02038',
 '02414',
 '02536',
 '02759',
 '03432',
 '03616',
 '03626',
 '04275',
 '04279',
 '04280',
 '04281',
 '043.1',
 '04302',
 '04312',
 '04313',
 '04321',
 '04322',
 '04326',
 '04337',
 '04347',
 '04348',
 '04349',
 '04351',
 '04352',
 '04355',
 '04374',
 '04376',
 '04380',
 '04384',
 '04387',
 '04388',
 '04390',
 '04391',
 '04396',
 '04399',
 '04401',
 '04402',
 '04403',
 '04404',
 '04405',
 '04406',
 '04407',
 '04408',
 '04433',
 '04434',
 '04435',
 '04436',
 '04437',
 '04438',
 '04441',
 '04443',
 '04455',
 '04456',
 '04457',
 '04458',
 '04475',
 '04478',
 '04558',
 '04936',
 '04968',
 '04970',
 '04971',
 '04973',
 '04974',
 '04977',
 '04980',
 '04981',
 '04982',
 '04983',
 '04984',
 '04985',
 '04986',
 '04989',
 '04990',
 '04992',
 '04993',
 '04994',
 '04995',
 '04996',
 '04997',
 '04999',
 '05000',
 '05001',
 '05002',
 '05003',
 '05004',
 '05005',
 '05006',
 '05007',
 '05008',
 '05009',
 '05010',
 '05011',
 '05012',
 '05013',
 '05015',
 '05016',
 '05019',
 '05021',
 '05022',
 '05023',
 '05024',
 '05025',
 '05026',
 '05027',
 '05028',
 '05029',
 '05032',
 '05033',
 '05034',
 '05035',
 '05038',
 '05040',
 '05042',
 '05044',
 '05045',
 '05047',
 '05048',
 '05049',
 '05052',
 '05054',
 '05055',
 '05058',
 '05059',
 '05060',
 '05061',
 '05062',
 '05063',
 '05064',
 '05065',
 '05066',
 '05067',
 '05068',
 '05069',
 '05072',
 '05074',
 '05075',
 '05077',
 '05079',
 '05080',
 '05081',
 '05082',
 '05083',
 '05084',
 '05086',
 '05087',
 '05087\n',
 '05088',
 '05090',
 '05091',
 '05094',
 '05097',
 '05098',
 '05100',
 '05101',
 '05102',
 '05103',
 '05107',
 '05111',
 '05112',
 '05113',
 '05115',
 '05116',
 '05117',
 '05119',
 '05120',
 '05123',
 '05125',
 '05126',
 '05128',
 '05129',
 '05131',
 '05132',
 '05133',
 '05135',
 '05136',
 '05141',
 '05143',
 '05144',
 '05146',
 '05147',
 '05152',
 '05154',
 '05157',
 '05158',
 '05162',
 '05166',
 '05172',
 '05173',
 '05175',
 '05177',
 '05178',
 '05180',
 '05181',
 '05182',
 '05185',
 '05187',
 '05188',
 '05192',
 '05193',
 '05194',
 '05195',
 '05196',
 '05198',
 '05200',
 '05203',
 '05205',
 '05207',
 '05210',
 '05211',
 '05213',
 '05214',
 '05215',
 '05219',
 '05220',
 '05222',
 '05223',
 '05224',
 '05225',
 '05226',
 '05228',
 '05229',
 '05233',
 '05236',
 '05237',
 '05238',
 '05240',
 '05241',
 '05242',
 '05244',
 '05245',
 '05246',
 '05247',
 '05248',
 '05249',
 '05250',
 '05250\n',
 '05251',
 '05252',
 '05253',
 '05254',
 '05255',
 '05256',
 '05257',
 '05258',
 '05259',
 '05260',
 '05261',
 '05264',
 '05265',
 '05291',
 '05298',
 '05300',
 '05304',
 '05310',
 '05311',
 '05312',
 '05313',
 '05314',
 '05315',
 '05316',
 '05322',
 '05323',
 '05324',
 '05325',
 '05327',
 '05328',
 '05332',
 '05335',
 '05337',
 '05338',
 '05339',
 '05340',
 '05343',
 '05344',
 '05345',
 '05346',
 '05349',
 '05350',
 '05350ยอ',
 '05351',
 '05352',
 '05354',
 '05355',
 '05356',
 '05357',
 '05358',
 '05359',
 '05360',
 '05361',
 '05363',
 '05365',
 '05366',
 '05367',
 '05368',
 '05370',
 '05371',
 '05373',
 '05378',
 '05386',
 '05391',
 '05392',
 '05393',
 '05394',
 '05395',
 '05396',
 '05399',
 '05413',
 '05414',
 '05415',
 '05416',
 '05418',
 '05419',
 '05422',
 '05423',
 '05424',
 '05425',
 '05428',
 '05431',
 '05432',
 '05433',
 '05434',
 '05435',
 '05436',
 '05437',
 '05439',
 '05440',
 '05441',
 '05442',
 '05541',
 '06238',
 '06251',
 '06253',
 '06254',
 '06255',
 '06256',
 '06257',
 '06259',
 '06260',
 '06261',
 '06263',
 '06265',
 '06267',
 '06268',
 '06270',
 '06271',
 '06272',
 '06273',
 '06274',
 '06275',
 '06276',
 '06277',
 '06278',
 '06279',
 '06280',
 '06281',
 '06282',
 '06283',
 '06285',
 '06286',
 '06287',
 '06288',
 '06289',
 '06290',
 '06291',
 '06292',
 '06293',
 '06294',
 '06295',
 '06296',
 '06297',
 '06298',
 '06299',
 '06300',
 '06301',
 '06302',
 '06307',
 '06308',
 '06309',
 '06310',
 '06311',
 '06312',
 '06314',
 '06315',
 '06316',
 '06318',
 '06319',
 '06320',
 '06321',
 '06322',
 '06323',
 '06324',
 '06325',
 '06326',
 '06327',
 '06328',
 '06329',
 '06330',
 '06331',
 '06332',
 '06333',
 '06334',
 '06521',
 '08485',
 '10360',
 '10673',
 '11010',
 '11055',
 '11056',
 '11057',
 '11059',
 '11060',
 '11066',
 '11069',
 '11070',
 '11072',
 '11073',
 '11084',
 '11088',
 '11111',
 '11111111',
 '11158',
 '11159',
 '11160',
 '11161',
 '11163',
 '11164',
 '11165',
 '11740',
 '11748',
 '11749',
 '11800',
 '11887',
 '13777',
 '13777t',
 '13937',
 '13941',
 '13943',
 '13943\n\n',
 '13944',
 '13946',
 '13947',
 '13948',
 '13949',
 '13952',
 '13953',
 '13954',
 '13955',
 '13962',
 '13963',
 '13966',
 '13984',
 '13987',
 '14005',
 '14007',
 '14280',
 '14284',
 '14843',
 '20510',
 '22222',
 '24622',
 '24650',
 '27988',
 '27990',
 '27998',
 '28017',
 '28691',
 '28789',
 '33333',
 '44902',
 '45972',
 '49741',
 '50210',
 '5271',
 '55555',
 '66666',
 '75757',
 '88888',
 '97255',
 '99795',
 '99999',
 'aaa',
 'bbb',
 'ccc',
 'eee',
 'fff',
 'ggg',
 'hhh',
 'iii',
 'jjj',
 'kkk',
 'lll',
 'mmm',
 'ppp',
 'qqq',
 'rrr',
 'sss',
 'test',
 'ttt',
 'uuu',
 'vvv',
 'www',
 'xxx',
 'yyy',
 'zzz'}

In [ ]:
drop_alldb = drop_alldb[(drop_alldb['site'].astype(str).str.isdigit()) & (drop_alldb['site'].str.len() == 5)] # เช็ค type ของข้อมูลโดยใช้ str.isdigit() และทำการเลือกข้อมูลที่เป็นตัวเลข 5 หลักเท่านั้น
drop_alldb

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13:08:39,มีตะกอน,0,0000
186,45-161,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",04312,09:45:28,ปกติ (เหลืองใส),0,0-1528
187,45-161,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",04312,10:06:45,ปกติ (เหลืองใส),0,0-1544
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000
190,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,00000
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,"iPhone14,2",99999,11:36:34,ขุ่น,1,99999
39813,99999,lnlohgqckf.png,2022-03-10,Samsung SM-G998B,99999,18:10:29,มีตะกอน,0,99999
39814,99999,vkdocpmjiv.png,2022-03-10,Samsung SM-G998B,99999,12:14:41,"ขุ่น, มีเม็ดเลือดแดง",1,99999
39815,99999,vrvyfnvayq.png,2022-03-10,Samsung SM-G998B,99999,13:58:01,ปกติ (เหลืองใส),1,99999
39816,99999,zuhbtvyrce.png,2022-03-10,Samsung SM-G998B,99999,13:57:58,ปกติ (เหลืองใส),1,99999

In [ ]:
new_hospital = data_hospital[['hcode','name','zone_code','zone_name','provincecode','province','amphurcode','amphur','tamboncode','tambon']] # ตัดให้เหลือ column ที่ต้องการนำไปใช้
new_hospital

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon
0,00001,สำนักงานสาธารณสุขจังหวัดสมุทรปราการ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,1.0,ปากน้ำ
1,00002,สำนักงานสาธารณสุขจังหวัดนนทบุรี,4,สาขาพื้นที่(สระบุรี),12.0,นนทบุรี,1.0,เมืองนนทบุรี,4.0,บางกระสอ
2,00003,สำนักงานสาธารณสุขจังหวัดปทุมธานี,4,สาขาพื้นที่(สระบุรี),13.0,ปทุมธานี,1.0,เมืองปทุมธานี,1.0,บางปรอก
3,00004,สำนักงานสาธารณสุขจังหวัดพระนครศรีอยุธยา,4,สาขาพื้นที่(สระบุรี),14.0,พระนครศรีอยุธยา,1.0,พระนครศรีอยุธยา,3.0,หอรัตนไชย
4,00005,สำนักงานสาธารณสุขจังหวัดอ่างทอง,4,สาขาพื้นที่(สระบุรี),15.0,อ่างทอง,1.0,เมืองอ่างทอง,8.0,บ้านอิฐ
...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น

In [ ]:
new_hospital.isnull().sum() # เช็คค่า missing

hcode             0
name              1
zone_code         0
zone_name         4
provincecode      1
province          0
amphurcode        2
amphur            2
tamboncode      168
tambon          209
dtype: int64

In [ ]:
drop_hospital = new_hospital.dropna() # จัดการค่า missing โดยการ drop 
drop_hospital

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon
0,00001,สำนักงานสาธารณสุขจังหวัดสมุทรปราการ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,1.0,ปากน้ำ
1,00002,สำนักงานสาธารณสุขจังหวัดนนทบุรี,4,สาขาพื้นที่(สระบุรี),12.0,นนทบุรี,1.0,เมืองนนทบุรี,4.0,บางกระสอ
2,00003,สำนักงานสาธารณสุขจังหวัดปทุมธานี,4,สาขาพื้นที่(สระบุรี),13.0,ปทุมธานี,1.0,เมืองปทุมธานี,1.0,บางปรอก
3,00004,สำนักงานสาธารณสุขจังหวัดพระนครศรีอยุธยา,4,สาขาพื้นที่(สระบุรี),14.0,พระนครศรีอยุธยา,1.0,พระนครศรีอยุธยา,3.0,หอรัตนไชย
4,00005,สำนักงานสาธารณสุขจังหวัดอ่างทอง,4,สาขาพื้นที่(สระบุรี),15.0,อ่างทอง,1.0,เมืองอ่างทอง,8.0,บ้านอิฐ
...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น

In [ ]:
# เช็คข้อมูลหลังจากการ drop ว่าหายไปกี่เปอร์เซ็นต์
removes = new_hospital.shape[0] - drop_hospital.shape[0]
print(f'size before drop = {new_hospital.shape[0]}')
print(f'size after drop = {drop_hospital.shape[0]}')
print(f'% from drop = {(removes/new_hospital.shape[0])*100}')

size before drop = 17103
size after drop = 16890
% from drop = 1.245395544641291

In [ ]:
set(drop_hospital['hcode']) # set ดูค่าที่เก็บไว้

{'02261',
 '23608',
 '04803',
 '03001',
 '26616',
 '05085',
 '12072',
 '03542',
 '77762',
 '24264',
 '05830',
 '08356',
 '08599',
 '18093',
 '24157',
 '25025',
 '06704',
 '06225',
 '09528',
 '99826',
 '14029',
 '06790',
 '09650',
 '00275',
 '02451',
 '27066',
 '07233',
 '05300',
 '14839',
 '23724',
 '03633',
 '04301',
 '16923',
 '23924',
 '25703',
 '13993',
 '11162',
 '00776',
 '10112',
 '25802',
 '07243',
 '01032',
 '27970',
 '00146',
 '01739',
 '01199',
 '08225',
 '13623',
 '01738',
 '10951',
 '77721',
 '02085',
 '11670',
 '01680',
 '03256',
 '25720',
 '01957',
 '01612',
 '06210',
 '03308',
 '07121',
 '10715',
 '13943',
 '07382',
 '26990',
 '07477',
 '04839',
 '11200',
 '02808',
 '08861',
 '03197',
 '11965',
 '04733',
 '25963',
 '05419',
 '11458',
 '06355',
 '11138',
 '00819',
 '25721',
 '10729',
 '14434',
 '14270',
 '07399',
 '07743',
 '00292',
 '05804',
 '09434',
 '03195',
 '09576',
 '19351',
 '06382',
 '01393',
 '19388',
 '04872',
 '03784',
 '00190',
 '24420',
 '07202',
 '04845',
 '14992',
 '10094',
 '28264',
 '05880',
 '28840',
 '04982',
 '11258',
 '11801',
 '08794',
 '10754',
 '01355',
 '09592',
 '24815',
 '13998',
 '25161',
 '08947',
 '05927',
 '01236',
 '23231',
 '00549',
 '24200',
 '07718',
 '10088',
 '09007',
 '24071',
 '00526',
 '00425',
 '05559',
 '03189',
 '05978',
 '25068',
 '25162',
 '27347',
 '07858',
 '03318',
 '18749',
 '07518',
 '24956',
 '02929',
 '03028',
 '01332',
 '26880',
 '28187',
 '04570',
 '08360',
 '22831',
 '23560',
 '05144',
 '24389',
 '02690',
 '10380',
 '24522',
 '02540',
 '14139',
 '10604',
 '07894',
 '00284',
 '07478',
 '01903',
 '02034',
 '24371',
 '06873',
 '07565',
 '07731',
 '07732',
 '10061',
 '05451',
 '05120',
 '01972',
 '25742',
 '06952',
 '24367',
 '24372',
 '04014',
 '11896',
 '28156',
 '10101',
 '01105',
 '11176',
 '09725',
 '03306',
 '25791',
 '09637',
 '07181',
 '21792',
 '28758',
 '03017',
 '03910',
 '07130',
 '03740',
 '14113',
 '09695',
 '01376',
 '01694',
 '09358',
 '02554',
 '07799',
 '04150',
 '04462',
 '13868',
 '11453',
 '05244',
 '15219',
 '24968',
 '77665',
 '21338',
 '00092',
 '11855',
 '02782',
 '02921',
 '03946',
 '08987',
 '07191',
 '09499',
 '28069',
 '09122',
 '00744',
 '02397',
 '02831',
 '16637',
 '03427',
 '06898',
 '02486',
 '06905',
 '12180',
 '13806',
 '04422',
 '14435',
 '28816',
 '06578',
 '03131',
 '11424',
 '02699',
 '09537',
 '02392',
 '06469',
 '15282',
 '08497',
 '28259',
 '09476',
 '06957',
 '06036',
 '24457',
 '09502',
 '00097',
 '25019',
 '05958',
 '03790',
 '01454',
 '10836',
 '08099',
 '10165',
 '13826',
 '16362',
 '99791',
 '05375',
 '09703',
 '02393',
 '03305',
 '10017',
 '77748',
 '22799',
 '23122',
 '01452',
 '04647',
 '05290',
 '00574',
 '09707',
 '12042',
 '12410',
 '02076',
 '09927',
 '24152',
 '01896',
 '05790',
 '08965',
 '10074',
 '00283',
 '09294',
 '26012',
 '07397',
 '09463',
 '10781',
 '11305',
 '01215',
 '04352',
 '23530',
 '01470',
 '23768',
 '01798',
 '14058',
 '00203',
 '05544',
 '27505',
 '02806',
 '06527',
 '11255',
 '00736',
 '04034',
 '03471',
 '22156',
 '04108',
 '00699',
 '07255',
 '09349',
 '02619',
 '04648',
 '27522',
 '99906',
 '00251',
 '11442',
 '09896',
 '04005',
 '24892',
 '09338',
 '04203',
 '08516',
 '26619',
 '02535',
 '06157',
 '07091',
 '23539',
 '15235',
 '77707',
 '14149',
 '26608',
 '26693',
 '00205',
 '05262',
 '04502',
 '13726',
 '07874',
 '11215',
 '24311',
 '00946',
 '01414',
 '11615',
 '24448',
 '00141',
 '07351',
 '05048',
 '10170',
 '11277',
 '07276',
 '12464',
 '01702',
 '01337',
 '06736',
 '01685',
 '11654',
 '07407',
 '10014',
 '08315',
 '00872',
 '05283',
 '07561',
 '05744',
 '14459',
 '08631',
 '19341',
 '03371',
 '15517',
 '17902',
 '01164',
 '06324',
 '11876',
 '24827',
 '25115',
 '25822',
 '11627',
 '05477',
 '11132',
 '11747',
 '24230',
 '01941',
 '10354',
 '02409',
 '21665',
 '09737',
 '20202',
 '00490',
 '00307',
 '08675',
 '09999',
 '10068',
 '12222',
 '14150',
 '07754',
 '02370',
 '05943',
 '10377',
 '02778',
 '03587',
 '01082',
 '10036',
 '03331',
 '08611',
 '01775',
 '27012',
 '10777',
 '06718',
 '07967',
 '02155',
 '00976',
 '03172',
 '09986',
 '11592',
 '24732',
 '04008',
 '10739',
 '14622',
 '05973',
 '08898',
 '02469',
 '04147',
 '00971',
 '02298',
 '28268',
 '03235',
 '02852',
 '28619',
 '01776',
 '00468',
 '06973',
 '01002',
 '03664',
 '06366',
 '08351',
 '13892',
 '10598',
 '04112',
 '24029',
 '05396',
 '03647',
 '04454',
 '26625',
 '07170',
 '23715',
 '02971',
 '16424',
 '04615',
 '24253',
 '07497',
 '08146',
 '07116',
 '11900',
 '02645',
 '02432',
 '05839',
 '04629',
 '06705',
 '07023',
 '22614',
 '24889',
 '03879',
 '09871',
 '19347',
 '28855',
 '04457',
 '00229',
 '11204',
 '10767',
 '01375',
 '00722',
 '04171',
 '06108',
 '07064',
 '08415',
 '77742',
 '06761',
 '05492',
 '26102',
 '03599',
 '04492',
 '10098',
 '17885',
 '06068',
 '11171',
 '27702',
 '24434',
 '15187',
 '03178',
 '03567',
 '10600',
 '27005',
 '02485',
 '11625',
 '00581',
 '05199',
 '14135',
 '24783',
 '08708',
 '03044',
 '28663',
 '03243',
 '01387',
 '15648',
 '03246',
 '25044',
 '27035',
 '23877',
 '10140',
 '02562',
 '27781',
 '01018',
 '24174',
 '04162',
 '01773',
 '09882',
 '77758',
 '04012',
 '05889',
 '10756',
 '27427',
 '02587',
 '01820',
 '14862',
 '09972',
 '08995',
 '09977',
 '26784',
 '24788',
 '01879',
 '02507',
 '05320',
 '23227',
 '07476',
 '24221',
 '26727',
 '01882',
 '12071',
 '06351',
 '07079',
 '08490',
 '08058',
 '08979',
 '23634',
 '05831',
 '10356',
 '19404',
 '04772',
 '24646',
 '11371',
 '10105',
 '08968',
 '02248',
 '09942',
 '10224',
 '07433',
 '12442',
 '00471',
 '06111',
 '25747',
 '01942',
 '00689',
 '06874',
 '05767',
 '22746',
 '23855',
 '24248',
 '13864',
 '24872',
 '05213',
 '10106',
 '00929',
 '08642',
 '00780',
 '00639',
 '00082',
 '04450',
 '23970',
 '25168',
 '09154',
 '07213',
 '09767',
 '07939',
 '04761',
 '09602',
 '22295',
 '22670',
 '04127',
 '22833',
 '08234',
 '24721',
 '04118',
 '07959',
 '08077',
 '25684',
 '07724',
 '08944',
 '19395',
 '24775',
 '07050',
 '11888',
 '27998',
 '28053',
 '25177',
 '05857',
 '04252',
 '03703',
 '01201',
 '28673',
 '04025',
 '01736',
 '12184',
 '09678',
 '26837',
 '06598',
 '02045',
 '02272',
 '07072',
 '15857',
 '06440',
 '11287',
 '11450',
 '02087',
 '28293',
 '01166',
 '01203',
 '02510',
 '05584',
 '77682',
 '07985',
 '06591',
 '00882',
 '11349',
 '05406',
 '28129',
 '00598',
 '23564',
 '04523',
 '26893',
 '28813',
 '06662',
 '07039',
 '00869',
 '02979',
 '01447',
 '15669',
 '23987',
 '05287',
 '04993',
 '09436',
 '11070',
 '09159',
 '09460',
 '04026',
 '10975',
 '01591',
 '05729',
 '11878',
 '12460',
 '06418',
 '04064',
 '14292',
 '15214',
 '26599',
 '24658',
 '26904',
 '08942',
 '07755',
 '03580',
 '09600',
 '15060',
 '24250',
 '09551',
 '02810',
 '09516',
 '25455',
 '11963',
 '77612',
 '22808',
 '24688',
 '07590',
 '24273',
 '11361',
 '06387',
 '00368',
 '13701',
 '24782',
 '02859',
 '19543',
 '25771',
 '06107',
 '06512',
 '22829',
 '05648',
 '03836',
 '05508',
 '05020',
 '03253',
 '06256',
 '09268',
 '07947',
 '01371',
 '25080',
 '02669',
 '06242',
 '10679',
 '01700',
 '14317',
 '04087',
 '09987',
 '06028',
 '28447',
 '03186',
 '08417',
 '11098',
 '99879',
 '07692',
 '10847',
 '14626',
 '24989',
 '10929',
 '28126',
 '05819',
 '26933',
 '03335',
 '01007',
 '05942',
 '03121',
 '09717',
 '10164',
 '01004',
 '05152',
 '06196',
 '01086',
 '17295',
 '09855',
 '04751',
 '25088',
 '18619',
 '14860',
 '09980',
 '07527',
 '09522',
 '24256',
 '28002',
 '09021',
 '05528',
 '05187',
 '10768',
 '27441',
 '28437',
 '04116',
 '01331',
 '08141',
 '08557',
 '26890',
 '07229',
 '11264',
 '15165',
 '06861',
 '08132',
 '09608',
 '28807',
 '09911',
 '04350',
 '13674',
 '07294',
 '19971',
 '06261',
 '06058',
 '06320',
 '00658',
 '02858',
 '11656',
 '00905',
 '05151',
 '08805',
 '03324',
 '08629',
 '10764',
 '14868',
 '24068',
 '24183',
 '15171',
 '01265',
 '04497',
 '04092',
 '25724',
 '24423',
 '27657',
 '26615',
 '08382',
 '04992',
 '08446',
 '99872',
 '01537',
 '13889',
 '16842',
 '02137',
 '04928',
 '05358',
 '07134',
 '11084',
 '08002',
 '14930',
 '01708',
 '06858',
 '03196',
 '15049',
 '17914',
 '00919',
 '06961',
 '25890',
 '16705',
 '07950',
 '11533',
 '08251',
 '00373',
 '26981',
 '05762',
 '03327',
 '07378',
 '26312',
 '06686',
 '24870',
 '04658',
 '24542',
 '28044',
 '09580',
 '07380',
 '99834',
 '03904',
 '08483',
 '25625',
 '26965',
 '13686',
 '01379',
 '03781',
 '27001',
 '25658',
 '03495',
 '27030',
 '28104',
 '12486',
 '15135',
 '04798',
 '24996',
 '09595',
 '14078',
 '27774',
 '10355',
 '15069',
 '04907',
 '07513',
 '00079',
 '04832',
 '07958',
 '14834',
 '24211',
 '05826',
 '02779',
 '08506',
 '01597',
 '05422',
 '01300',
 '07086',
 '23995',
 '13670',
 '28108',
 '05043',
 '06763',
 '06937',
 '09188',
 '11962',
 '28285',
 '02317',
 '08957',
 '28298',
 '06569',
 '00170',
 '09847',
 '28233',
 '99894',
 '13941',
 '03575',
 '09975',
 '02844',
 '08494',
 '05572',
 '09875',
 '07557',
 '00502',
 '05218',
 '05883',
 '03061',
 '02281',
 '14775',
 '25028',
 '08038',
 '16429',
 '01341',
 '09657',
 '06262',
 '05000',
 '11036',
 '23030',
 '19349',
 '10792',
 '26343',
 '02214',
 '02919',
 '23867',
 '01914',
 '22868',
 '07941',
 '10750',
 '03238',
 '03997',
 '11532',
 '04383',
 '04003',
 '05232',
 '05177',
 '04529',
 '11393',
 '14035',
 '24215',
 '03220',
 '03458',
 '07769',
 '08669',
 '27456',
 '23607',
 '02657',
 '19354',
 '13916',
 '13994',
 '07714',
 '17458',
 '06537',
 '12261',
 '11741',
 '27480',
 '07995',
 '04599',
 '15667',
 '00015',
 '02358',
 '24953',
 '02118',
 '27365',
 '09889',
 '03560',
 '06557',
 '05872',
 '06618',
 '04402',
 '01157',
 '09666',
 '07252',
 '04813',
 '00312',
 '06567',
 '01021',
 '02822',
 '08511',
 '10179',
 '21438',
 '07265',
 '03602',
 '77741',
 '11047',
 '24419',
 '28835',
 '10439',
 '12230',
 '21519',
 '02229',
 '03796',
 '04598',
 '01439',
 '06200',
 '77770',
 '06677',
 '24143',
 '25994',
 '07535',
 '16313',
 '21708',
 '00310',
 '05346',
 '05813',
 '04897',
 '06395',
 '10959',
 '14691',
 '04235',
 '08231',
 '08359',
 '11376',
 '00911',
 '23822',
 '10405',
 '08163',
 '19338',
 '03357',
 '10972',
 ...}

## รวมตารางข้อมูล alldb และ hospital เข้าด้วยกัน โดยใช้การ merge

In [ ]:
data = drop_alldb.merge(drop_hospital,how='left',left_on='site',right_on='hcode') # เชื่อมตารางโดยตารางทางซ้ายเป็น alldb มี key คือ site เชื่อมกับ hospital มี key คือ hcode
data

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon
0,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13:08:39,มีตะกอน,0,0000,05194,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านหนองหว้า ตำบลกก...,7.0,สาขาพื้นที่(ขอนแก่น),45.0,ร้อยเอ็ด,9.0,หนองพอก,4.0,กกโพธิ์
1,45-161,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",04312,09:45:28,ปกติ (เหลืองใส),0,0-1528,04312,โรงพยาบาลส่งเสริมสุขภาพตำบลสีชมพู,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,6.0,สีชมพู,1.0,สีชมพู
2,45-161,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",04312,10:06:45,ปกติ (เหลืองใส),0,0-1544,04312,โรงพยาบาลส่งเสริมสุขภาพตำบลสีชมพู,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,6.0,สีชมพู,1.0,สีชมพู
3,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000,04999,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านเปลือย,7.0,สาขาพื้นที่(ขอนแก่น),44.0,มหาสารคาม,6.0,บรบือ,19.0,หนองโก
4,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,00000,13777,โรงพยาบาลศรีนครินทร์ มหาวิทยาลัยขอนแก่น,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,1.0,เมืองขอนแก่น,1.0,ในเมือง
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38354,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,"iPhone14,2",99999,11:36:34,ขุ่น,1,99999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38355,99999,lnlohgqckf.png,2022-03-10,Samsung SM-G998B,99999,18:10:29,มีตะกอน,0,99999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38356,99999,vkdocpmjiv.png,2022-03-10,Samsung SM-G998B,99999,12:14:41,"ขุ่น, มีเม็ดเลือดแดง",1,99999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38357,99999,vrvyfnvayq.png,2022-03-10,Samsung SM-G998B,99999,13:58:01,ปกติ (เหลืองใส),1,99999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38358,99999,zuhbtvyrce.png,2022-03-10,Samsung SM-G998B,99999,13:57:58,ปกติ (เหลืองใส),1,99999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.isnull().sum() # เช็คค่า missing

user             0
RowKey           0
date             0
phone            0
site             0
time             0
urine            0
ov               0
PartitionKey     0
hcode           84
name            84
zone_code       84
zone_name       84
provincecode    84
province        84
amphurcode      84
amphur          84
tamboncode      84
tambon          84
dtype: int64

In [ ]:
drop_data = data.dropna() # จัดการค่า missing โดยการ drop
drop_data

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon
0,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13:08:39,มีตะกอน,0,0000,05194,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านหนองหว้า ตำบลกก...,7.0,สาขาพื้นที่(ขอนแก่น),45.0,ร้อยเอ็ด,9.0,หนองพอก,4.0,กกโพธิ์
1,45-161,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",04312,09:45:28,ปกติ (เหลืองใส),0,0-1528,04312,โรงพยาบาลส่งเสริมสุขภาพตำบลสีชมพู,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,6.0,สีชมพู,1.0,สีชมพู
2,45-161,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",04312,10:06:45,ปกติ (เหลืองใส),0,0-1544,04312,โรงพยาบาลส่งเสริมสุขภาพตำบลสีชมพู,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,6.0,สีชมพู,1.0,สีชมพู
3,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000,04999,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านเปลือย,7.0,สาขาพื้นที่(ขอนแก่น),44.0,มหาสารคาม,6.0,บรบือ,19.0,หนองโก
4,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,00000,13777,โรงพยาบาลศรีนครินทร์ มหาวิทยาลัยขอนแก่น,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,1.0,เมืองขอนแก่น,1.0,ในเมือง
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38338,76331,pvpiawlexb.png,2022-02-23,Samsung SM-G965U,05258,15:32:53,ปกติ (เหลืองใส),1,92,05258,โรงพยาบาลส่งเสริมสุขภาพตำบลหนองตาโฮม ตำบลขี้เหล็ก,7.0,สาขาพื้นที่(ขอนแก่น),45.0,ร้อยเอ็ด,14.0,อาจสามารถ,9.0,ขี้เหล็ก
38339,68317,rtutxrlbam.png,2022-02-23,Samsung SM-A115F,28017,14:31:01,ปกติ (เหลืองใส),2,976,28017,โรงพยาบาลนาคู,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,16.0,นาคู,1.0,นาคู
38340,68317,dmuragqwza.png,2022-02-23,Samsung SM-A115F,28017,14:30:21,ปกติ (เหลืองใส),2,983,28017,โรงพยาบาลนาคู,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,16.0,นาคู,1.0,นาคู
38341,68768,D8A3A9EA-929E-4CEB-BFDF-C9BE093EA663,2022-03-24,"iPhone11,8",11088,10:25:32,ปกติ (เหลืองใส),1,99444,11088,โรงพยาบาลห้วยผึ้ง,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง
38342,99771,E04D3D60-B916-40A1-AE77-91CCD89DD084,2022-03-31,"iPhone10,5",05396,11:03:40,ปกติ (เหลืองใส),0,99771,05396,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านสูงเนิน,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,10.0,คำม่วง,9.0,เนินยาง

In [ ]:
# เช็คข้อมูลหลังจากการ drop ว่าหายไปกี่เปอร์เซ็นต์
removes = data.shape[0] - drop_data.shape[0]
print(f'size before drop = {data.shape[0]}')
print(f'size after drop = {drop_data.shape[0]}')
print(f'% from drop = {(removes/data.shape[0])*100}')

size before drop = 38359
size after drop = 38275
% from drop = 0.21898381083969862

## เปลี่ยน type ข้อมูล

In [ ]:
drop_data.info() # เช็ค type ข้อมูล

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38275 entries, 0 to 38342
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user          38275 non-null  object
 1   RowKey        38275 non-null  object
 2   date          38275 non-null  object
 3   phone         38275 non-null  object
 4   site          38275 non-null  object
 5   time          38275 non-null  object
 6   urine         38275 non-null  object
 7   ov            38275 non-null  object
 8   PartitionKey  38275 non-null  object
 9   hcode         38275 non-null  object
 10  name          38275 non-null  object
 11  zone_code     38275 non-null  float64
 12  zone_name     38275 non-null  object
 13  provincecode  38275 non-null  float64
 14  province      38275 non-null  object
 15  amphurcode    38275 non-null  float64
 16  amphur        38275 non-null  object
 17  tamboncode    38275 non-null  float64
 18  tambon        38275 non-null  object
dtypes: float64(4), object(15)
memory usage: 5.8+ MB

In [ ]:
# ทำการเปลี่ย type ของข้อมูล
drop_data['RowKey'] = drop_data['RowKey'].astype('string')
drop_data['phone'] = drop_data['phone'].astype('string')
drop_data['urine'] = drop_data['urine'].astype('string')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

## จัดการให้ค่า user เป็นตัวเลข 5 หลัก(ตัวเลขเท่านั้น)

In [ ]:
set(drop_data['user']) # set ดูค่าที่เก็บไว้

{'06268',
 '71417',
 '00028',
 '43431',
 '50063',
 '80253',
 '60909',
 '40520',
 '00011',
 '21955',
 '29025',
 '00212',
 '32077',
 '28348',
 '70940',
 '02784',
 '06790',
 '88023',
 '52066',
 '47157',
 '01248',
 '98509',
 '59476',
 '99245',
 '83934',
 '73375',
 '76486',
 '00146',
 '51689',
 '49782',
 '03308',
 '27678',
 '94454',
 '29417',
 '26990',
 '33553',
 '19265',
 '05082',
 '71872',
 '00032',
 '4',
 '24563',
 '25721',
 '00270',
 '14387',
 '21045',
 '00292',
 '90609',
 '61218',
 '48768',
 '75838',
 '26540',
 '00190',
 '65388',
 '84375',
 '45752',
 '87181',
 '83276',
 '84935',
 '47933',
 '61591',
 '24846',
 '63200',
 '55365',
 '23231',
 '05974',
 '47950',
 '24641',
 '76105',
 '54427',
 '80511',
 '87771',
 '22244',
 '63564',
 '11055',
 '65390',
 '37216',
 '92120',
 '3450100805222',
 '66501',
 '12786',
 '58993',
 '00126',
 '33791',
 '17790',
 '00006',
 '00284',
 '97461',
 '99835',
 '80289',
 '22722',
 '03338',
 '52724',
 '70973',
 '39448',
 '48016',
 '87697',
 '87315',
 '03831',
 '23630',
 '77665',
 '67280',
 '00004',
 '14360',
 '05211',
 '19875',
 '37151',
 '32171',
 '17769',
 '00341',
 '56004',
 '92756',
 '00047',
 '00216',
 '42468',
 '31755',
 '57228',
 '83771',
 '34331',
 '83659',
 '26776',
 '86981',
 '31982',
 '12605',
 '22545',
 '00172',
 '15734',
 '3451100451251',
 '81293',
 '50144',
 '61359',
 '91209',
 '00016',
 '80481',
 '31811',
 '78731',
 '00283',
 '72364',
 '14491',
 '89475',
 '00196',
 '25331',
 '18253',
 '22421',
 '87394',
 '66062',
 '61265',
 '00203',
 '04405',
 '73876',
 '54468',
 '73496',
 '97831',
 '00253',
 '00251',
 '17415',
 '77726',
 '89394',
 '18025',
 '61552',
 '41951',
 '16144',
 '12044',
 '37691',
 '00205',
 '79620',
 '96417',
 '90604',
 '89681',
 '26462',
 '11215',
 '11891',
 '19411',
 '15102',
 '24622',
 '89329',
 '00141',
 '19250',
 '39079',
 '54192',
 '94558',
 '24404',
 '54544',
 '3451400598487',
 '88315',
 '46951',
 '77670',
 '11611',
 '23675',
 '25179',
 '00176',
 '50172',
 '32468',
 '86721',
 '00307',
 '14988',
 '51065',
 '36692',
 '74782',
 '00083',
 '67961',
 '06079',
 '00022',
 '61121',
 '16754',
 '89913',
 '87029',
 '78673',
 '65632',
 '94758',
 '54923',
 '04193',
 '74951',
 '71970',
 '45783',
 '76011',
 '85753',
 '00153',
 '45914',
 '24501',
 '84276',
 '28992',
 '96481',
 '00074',
 '44502',
 '45680',
 '63753',
 '20606',
 '65995',
 '90571',
 '56051',
 '70059',
 '3451100150251',
 '36385',
 '39638',
 '00027',
 '72483',
 '01882',
 '25466',
 '35942',
 '02396',
 '05135',
 '61044',
 '61813',
 '00017',
 '75347',
 '10105',
 '34210',
 '01942',
 '00162',
 '97860',
 '01428',
 '49741',
 '48274',
 '07644',
 '67379',
 '00082',
 '99884',
 '58814',
 '53089',
 '27802',
 '55806',
 '26445',
 '19920',
 '78334',
 '00009',
 '28399',
 '37408',
 '49215',
 '11808',
 '48962',
 '48042',
 '25219',
 '50756',
 '02087',
 '34829',
 '50276',
 '02091',
 '71327',
 '50047',
 '00169',
 '49268',
 '00545',
 '52678',
 '34343',
 '29271',
 '09343',
 '97770',
 '44364',
 '63852',
 '89381',
 '17536\n\n17536',
 '87536',
 '74289',
 '52147',
 '32949',
 '92241',
 '60879',
 '86545',
 '29000',
 '22542',
 '32625',
 '06283',
 '34317',
 '27529',
 '75771',
 '47061',
 '11361',
 '7140',
 '54932',
 '72451',
 '15737',
 '94150',
 '88351',
 '90770',
 '41000',
 '67972',
 '92545',
 '18318',
 '78486',
 '76299',
 '46415',
 '18733',
 '38771',
 '00624',
 '03359',
 '94279',
 '55300',
 '40035',
 '65509',
 '14914',
 '38518',
 '80673',
 '63951',
 '74338',
 '92220',
 '  67241\n',
 '50332',
 '84196',
 '59226',
 '17982',
 '83733',
 '00756',
 '31534',
 '3450101325119',
 '05151',
 '53041',
 '57099',
 '82951',
 '73336',
 '20690',
 '13088',
 '50951',
 '52131',
 '85493',
 '03409',
 '17974',
 '42453',
 '44509',
 '05358',
 '74375',
 '97057',
 '22377',
 '18849',
 '00565',
 '80336',
 '87374',
 '77254',
 '84495',
 '13361',
 '02663',
 '89056',
 '64612',
 '63381',
 '00285',
 '90872',
 '30016',
 '86483',
 '96081',
 '29907',
 '33739',
 '37228',
 '47593',
 '29309',
 '74747',
 '29875',
 '95927',
 '76096',
 '83937',
 '79493',
 '53481',
 '51301',
 '00079',
 '60181',
 '46897',
 '52210',
 '79525',
 '10695',
 '09006',
 '83303',
 '00286',
 '09188',
 '32200',
 '67094',
 '00170',
 '34096',
 '05219',
 '23338',
 '30511',
 '46948',
 '26511',
 '97255',
 '75910',
 '10992',
 '47429',
 '74335',
 '95810',
 '47844',
 '58271',
 '43868',
 '62440',
 '05272',
 '91917',
 '46481',
 '77358',
 '63018',
 '05232',
 '71152',
 '71378',
 '71813',
 '00274',
 '92962',
 '26469',
 '00015',
 '65301',
 '05116',
 '28731',
 '04402',
 '99011',
 '00345',
 '38727',
 '00312',
 '32666',
 '12015',
 '97308',
 '97013',
 '73381',
 '94881',
 '46960',
 '00302',
 '30024',
 '59423',
 '43834',
 '00342',
 '88377',
 '27143',
 '00010',
 '44199',
 '55659',
 '28291',
 '47135',
 '19737',
 '00268',
 '59144',
 'ttohn',
 '20395',
 '19559',
 '10405',
 '82054',
 '46627',
 '50577',
 '00317',
 '80175',
 '50471',
 '86601',
 '00134',
 '00399',
 '00149',
 '68768',
 '33503',
 '28062',
 '82277',
 '40533',
 '25804',
 '45047',
 '81057',
 '83943',
 '10120',
 '29760',
 '23554',
 '94295',
 '65321',
 '17916',
 '89195',
 '08021',
 '16214',
 '12576',
 '74378',
 '37914',
 '46775',
 '20304',
 '39529',
 '77509',
 '84374',
 '22824',
 '80734',
 '16675',
 '17777',
 '71228',
 '11111',
 '67409',
 '37732',
 '89251',
 '05228',
 '97290',
 '71805',
 '00139',
 '02594',
 '52830',
 '90257',
 '00048',
 '58668',
 '00112',
 '83900',
 '21432',
 '00195',
 '93527',
 '44018',
 '16970',
 '3460500500020',
 '00167',
 '77576',
 '16085',
 '94414',
 '43228',
 '05047',
 '31322',
 '26442',
 '04461',
 '26082',
 '17184',
 '84005',
 '00322',
 '97016',
 '07573',
 '86133',
 '96730',
 '80979',
 '01408',
 '59721',
 '70370',
 '65664',
 '86407',
 '00178',
 '11387',
 '96292',
 '52921',
 '41042',
 '10993',
 '05590',
 '62443',
 '79817',
 '5451100055352',
 '55239',
 '00277',
 '62241',
 '10982',
 '78901',
 '49161',
 '46597',
 '12561',
 '69556',
 '73038',
 '40591\n40591\n',
 '05039',
 '50727',
 '3451100324624',
 '30121',
 '10487',
 '00005',
 '86050',
 '21177',
 '54761',
 '70671',
 '00036',
 '94538',
 '5799',
 '34988',
 '29999',
 '20452',
 '13312',
 '57066',
 '00001',
 '00050',
 '92431',
 '49424',
 '42370',
 '73233',
 '69911',
 '05374',
 '65555',
 '68317',
 '41937',
 '16174',
 '61325',
 '52180',
 '76331',
 '80847',
 '19241',
 '24032',
 '74345',
 '78054',
 '63477',
 '00197',
 '27046',
 '09820',
 '16904',
 '00041',
 '45563',
 '86113',
 '52209',
 '65775',
 '95193',
 '98126',
 '3451100324713',
 '89576',
 '88708',
 '64385',
 '00159',
 '05304',
 '81621',
 '53751',
 '57954',
 '51241',
 '26440',
 '3450101229373',
 '20847',
 '52665',
 '37551',
 '63865',
 '11887',
 '65733',
 '00202',
 '59326',
 '54788',
 '36593',
 '  noknoi2601@gmail.com\n',
 '94988',
 '49634',
 '95821',
 '64817',
 '02518',
 '00144',
 '83257',
 '00213',
 '15731',
 '00030',
 '69431',
 '65675',
 '45729',
 '76523',
 '15046',
 '87738',
 '80382',
 '91811',
 '83449',
 '06855',
 '33237',
 '13070',
 '77572',
 '84494',
 '35512',
 '05961',
 '04854',
 '25943',
 '01431',
 '17564',
 '86588',
 '63880',
 '55430',
 '02913',
 '81724',
 '62941',
 '50837',
 '70810',
 '32891',
 '93884',
 '73445',
 '39593',
 '76819',
 '00263',
 '07556',
 '00300',
 '19202',
 '53616',
 '22804',
 '88135',
 '33643',
 '00164',
 '92747',
 '49322',
 '92648',
 '30431',
 '14505',
 '21688',
 '73419',
 '01312',
 '00046',
 '00224',
 '88538',
 '1450700099250',
 '42682',
 '34585',
 '00039',
 '00034',
 '3451100141252',
 '00161',
 '89837',
 '18890',
 '63910',
 '27732',
 '02075',
 '93991',
 '54974',
 '49103',
 '90817',
 '14088',
 '20291',
 '50580',
 '19527',
 '03953',
 '63068',
 '16820',
 '77645',
 '37607',
 '10518',
 '75251',
 '81065',
 '05849',
 '95935',
 '25199',
 '76803',
 '00278',
 '36994',
 '3451100451758',
 '30041',
 '53330',
 '55873',
 '82894',
 '27129',
 '29051',
 '49308',
 '00150',
 '77811',
 '80317',
 '11159',
 '00049',
 '26651',
 '79028',
 '29514',
 '89470',
 '00305',
 '66155',
 '98908',
 '04387',
 '83662',
 '60688',
 '97913',
 '00290',
 '00315',
 '31133',
 '78494',
 '38614',
 '72186',
 '82685',
 '00115',
 '96706',
 '29118',
 '31401',
 '19578',
 '63748',
 '11727',
 '25221',
 '50284',
 '32622',
 '91645',
 '00198',
 '84459',
 '18402',
 '00306',
 '84540',
 '84768',
 '31582',
 '05368',
 '37091',
 '79066',
 '69681',
 '66261',
 '91402',
 '96699',
 '00043',
 '28743',
 '00941',
 '35888',
 '25071',
 '00219',
 '00128',
 '59266',
 '58718',
 '12378',
 '00218',
 '00237',
 '97965',
 '54281',
 '18769',
 '03949',
 '3400900747146',
 '98080',
 '00404',
 '04281',
 '98530',
 '45701',
 '46341',
 '00155',
 '14835',
 '04347',
 '23186',
 '36358',
 '01008',
 '47607',
 '66771',
 '16783',
 '3451100146637',
 '10046',
 '09902',
 '16428',
 '70196',
 '10673',
 '46783',
 '41026',
 '60887',
 '19624',
 '03421',
 '23078',
 '02102',
 '37231',
 '89081',
 '55911',
 '72169',
 '74493',
 '66381',
 '18865',
 '91947',
 '75126',
 '20435',
 '89493',
 '54100',
 '61605',
 '86542',
 '75487',
 '39342',
 '00180',
 '05663',
 '63429',
 '60953',
 '03649',
 '43657',
 '55547',
 '32310',
 '28593',
 '00148',
 '00194',
 '02897',
 '99992',
 '96630',
 '00308',
 '49178',
 '00131',
 '64081',
 '85433',
 '10724',
 '51568',
 '3450101576642',
 '3450101325593',
 '42120',
 '04388',
 '50802',
 '11198',
 '32999',
 '22455',
 '11165',
 '40828',
 '27503',
 '17132',
 '71921',
 '00157',
 '81409',
 '26043',
 '29391',
 '76339',
 '32581',
 '01721',
 '00208',
 '31143',
 '02217',
 '00313',
 '89290',
 '22692',
 '51892',
 '01024',
 '82822',
 '00121',
 '74103',
 '95161',
 '10264',
 '99376',
 '67093',
 '19130',
 '08971',
 '00073',
 '04431',
 '14884',
 '34169',
 '75841',
 '55865',
 '23596',
 '16725',
 '94494',
 '58870',
 '05019',
 '98703',
 '00166',
 '38463',
 '86774',
 '00053',
 '42228',
 '72938',
 '02579',
 '46732',
 '75835',
 '7197',
 '78251',
 '59269',
 '84493',
 '75579',
 '94392',
 '08236',
 '85737',
 '61806',
 '74367',
 '39726',
 '96760',
 '73204',
 '82582',
 '28186',
 '00120',
 '50373',
 '00045',
 '22635',
 '46520',
 '85702',
 '36362',
 '30067',
 '85934',
 '72225',
 '00215',
 '20827',
 '96099',
 '62768',
 '46291',
 '00154',
 '42173',
 '44888',
 '56044',
 '19201',
 '14771',
 '03558',
 '03087',
 '79834',
 '14891',
 '54781',
 '14390',
 '34409',
 '00182',
 '01009',
 '75061',
 '87468',
 '03381',
 '00293',
 '68162',
 '3450100543961',
 '74891',
 '09259',
 '32082',
 '21378',
 '00174',
 '73772',
 '44902',
 '04221',
 '32831',
 ...}

In [ ]:
drop_data = drop_data[(drop_data['user'].astype(str).str.isdigit()) & (drop_data['user'].str.len() == 5)] # เช็ค type ของข้อมูลโดยใช้ str.isdigit() และทำการเลือกข้อมูลที่เป็นตัวเลข 5 หลักเท่านั้น
drop_data

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon
0,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13:08:39,มีตะกอน,0,0000,05194,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านหนองหว้า ตำบลกก...,7.0,สาขาพื้นที่(ขอนแก่น),45.0,ร้อยเอ็ด,9.0,หนองพอก,4.0,กกโพธิ์
3,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000,04999,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านเปลือย,7.0,สาขาพื้นที่(ขอนแก่น),44.0,มหาสารคาม,6.0,บรบือ,19.0,หนองโก
4,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,00000,13777,โรงพยาบาลศรีนครินทร์ มหาวิทยาลัยขอนแก่น,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,1.0,เมืองขอนแก่น,1.0,ในเมือง
5,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14:46:08,ปกติ (เหลืองใส),4,00001,06307,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านเกาะ ตำบลบ้านดารา,2.0,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,7.0,พิชัย,2.0,บ้านดารา
6,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15:27:45,ปกติ (เหลืองใส),4,00001,05328,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านโคกประสิทธิ์,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,18.0,ฆ้องชัย,3.0,โคกสะอาด
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38338,76331,pvpiawlexb.png,2022-02-23,Samsung SM-G965U,05258,15:32:53,ปกติ (เหลืองใส),1,92,05258,โรงพยาบาลส่งเสริมสุขภาพตำบลหนองตาโฮม ตำบลขี้เหล็ก,7.0,สาขาพื้นที่(ขอนแก่น),45.0,ร้อยเอ็ด,14.0,อาจสามารถ,9.0,ขี้เหล็ก
38339,68317,rtutxrlbam.png,2022-02-23,Samsung SM-A115F,28017,14:31:01,ปกติ (เหลืองใส),2,976,28017,โรงพยาบาลนาคู,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,16.0,นาคู,1.0,นาคู
38340,68317,dmuragqwza.png,2022-02-23,Samsung SM-A115F,28017,14:30:21,ปกติ (เหลืองใส),2,983,28017,โรงพยาบาลนาคู,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,16.0,นาคู,1.0,นาคู
38341,68768,D8A3A9EA-929E-4CEB-BFDF-C9BE093EA663,2022-03-24,"iPhone11,8",11088,10:25:32,ปกติ (เหลืองใส),1,99444,11088,โรงพยาบาลห้วยผึ้ง,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง
38342,99771,E04D3D60-B916-40A1-AE77-91CCD89DD084,2022-03-31,"iPhone10,5",05396,11:03:40,ปกติ (เหลืองใส),0,99771,05396,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านสูงเนิน,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,10.0,คำม่วง,9.0,เนินยาง

## เปลี่ยน date เป็น YYYY-MM-DD

In [ ]:
drop_data['date'] = pd.to_datetime(drop_data['date'],format="%Y/%m/%d") # เปลี่ยน format ของข้อมูลวันที่ให้อยู่ในรูปแบบเดียวกัน
drop_data[['date']]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

            date
0     2022-03-24
3     2022-02-25
4     2022-03-23
5     2022-03-30
6     2022-03-30
...          ...
38338 2022-02-23
38339 2022-02-23
38340 2022-02-23
38341 2022-03-24
38342 2022-03-31

[37890 rows x 1 columns]

## เปลี่ยน time เป็น hh-mm-ss

In [ ]:
drop_data['time'] = pd.to_datetime(drop_data['time'],format='%H:%M%:%S',errors='ignore') # เปลี่ยน format ของข้อมูลเวลาให้อยู่ในรูปแบบเดียวกัน
drop_data[['time']]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

           time
0      13:08:39
3      14:22:22
4      16:31:45
5      14:46:08
6      15:27:45
...         ...
38338  15:32:53
38339  14:31:01
38340  14:30:21
38341  10:25:32
38342  11:03:40

[37890 rows x 1 columns]

## จัดการให้ค่า ov เป็นตัวเลข มีค่าตั้งแต่ 0-4 (0 คือไม่พบโรค 1-4 คือพบโรคที่ระดับความรุนแรงต่างๆ)

In [ ]:
set(drop_data['ov']) # set ดูค่าที่เก็บไว้

{'0', '1', '2', '3', '4', 'ติดเชื้อ +2 '}

In [ ]:
drop_data[drop_data['ov'] == 'ติดเชื้อ +2 '] # ดูว่า 'ติดเชื้อ +2 ' เป็นค่าที่เท่าไร

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon
16413,87374,A838A03E-1327-4720-B689-FD29C78023FD,2022-03-07,"iPhone8,2",05237,11:50:47,ปกติ (เหลืองใส),ติดเชื้อ +2,00187,05237,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านจานเตย ตำบลทุ...,7.0,สาขาพื้นที่(ขอนแก่น),45.0,ร้อยเอ็ด,11.0,สุวรรณภูมิ,13.0,ทุ่งกุลา

In [ ]:
drop_data['ov'] = drop_data['ov'].drop(16413) # drop ค่า 'ติดเชื้อ +2 ' ทิ้ง

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
drop_data = drop_data.dropna(subset=['ov']) # จัดการค่า missing

In [ ]:
set(drop_data['ov']) # เช็คค่าที่เก็บไว้

{'0', '1', '2', '3', '4'}

## จัดการให้ค่า PartitionKey เป็นตัวเลข 5 หลัก(ตัวเลขเท่านั้น)

In [ ]:
set(drop_data['PartitionKey']) # set ดูค่าที่เก็บไว้

{'02304',
 '00028',
 '06049',
 '00011',
 '03542',
 '01544',
 '02120',
 '00212',
 '02472',
 '03133',
 '05830',
 '02653',
 '02701',
 '01167',
 '00720',
 '02784',
 '02912',
 '00275',
 '02143',
 '02451',
 '02991',
 '01424',
 '03107',
 '01248',
 '00973',
 '10996',
 '01576',
 '00776',
 '01032',
 '00146',
 '01739',
 '01199',
 '02029',
 '05991',
 '02771',
 '01738',
 '02085',
 '00333',
 '01680',
 '02976',
 '00521',
 '01957',
 '01612',
 '00838',
 '01778',
 '02808',
 '00541',
 '200',
 '01725',
 '00427',
 '03197',
 '08904',
 '05780',
 '01047',
 '00608',
 '02904',
 '89',
 '00032',
 '00734',
 '09011',
 '00716',
 '00819',
 '00058',
 '00270',
 '01595',
 '03221',
 '00292',
 '00370',
 '00786',
 '000102',
 '00742',
 '01251',
 '01393',
 '00532',
 '01809',
 '01897',
 '03245',
 '03255',
 '00190',
 '00119',
 '01028',
 '00957',
 '03824',
 '01910',
 '04137',
 '05981',
 '01361',
 '01069',
 '01355',
 '02195',
 '06723',
 '00495',
 '08947',
 '00632',
 '01236',
 '00337',
 '01247',
 '00470',
 '00549',
 '03168',
 '04691',
 '05974',
 '09007',
 '00526',
 '00425',
 '01585',
 '03189',
 '01975',
 '03108',
 '04623',
 '193',
 '00099',
 '02929',
 '01469',
 '02883',
 '01332',
 '00768',
 '00449',
 '00852',
 '08924',
 '00126',
 '02989',
 '01652',
 '01878',
 '00006',
 '00717',
 '01100',
 '02540',
 '01381',
 '02690',
 '08976',
 '00284',
 '01397',
 '01903',
 '02034',
 '00344',
 '00095',
 '00228',
 '02024',
 '05120',
 '01972',
 '08912',
 '02968',
 '03008',
 '09036',
 '03338',
 '04014',
 '03507',
 '02032',
 '01105',
 '01523',
 '05724',
 '06051',
 '03290',
 '00354',
 '01376',
 '01694',
 '02561',
 '05244',
 '05092',
 '01295',
 '00092',
 '01159',
 '02782',
 '00004',
 '02046',
 '03362',
 '03124',
 '08987',
 '08572',
 '03034',
 '00744',
 '01296',
 '02044',
 '02397',
 '00522',
 '02486',
 '00341',
 '00857',
 '01478',
 '01549',
 '03284',
 '3450101522372',
 '08962',
 '00513',
 '00047',
 '00216',
 '02319',
 '03278',
 '01839',
 '241',
 '01432',
 '00939',
 '01998',
 '06729',
 '01339',
 '00674',
 '01318',
 '00361',
 '06036',
 '00063',
 '01821',
 '01059',
 '00097',
 '05958',
 '02103',
 '01454',
 '06061',
 '00458',
 '00172',
 '03056',
 '08914',
 '04633',
 '00883',
 '01270',
 '00016',
 '03332',
 '03305',
 '01847',
 '04812',
 '00952',
 '01452',
 '05290',
 '00574',
 '01151',
 '01426',
 '00770',
 '02076',
 '02292',
 '01713',
 '01896',
 '02777',
 '08965',
 '00283',
 '00196',
 '00707',
 '03144',
 '00098',
 '01215',
 '02555',
 '02600',
 '00714',
 '01470',
 '08943',
 '05209',
 '01003',
 '01798',
 '01121',
 '00395',
 '00203',
 '06011',
 '01187',
 '09005',
 '01959',
 '29',
 '00736',
 '00849',
 '00985',
 '00699',
 '04665',
 '02619',
 '00253',
 '00798',
 '04648',
 '00251',
 '03403',
 '00667',
 '01864',
 '02563',
 '02952',
 '01787',
 '03376',
 '01996',
 '02200',
 '00718',
 '00205',
 '03078',
 '05262',
 '01933',
 '00672',
 '0000',
 '01509',
 '00946',
 '01414',
 '01530',
 '06145',
 '00141',
 '01605',
 '03424',
 '01661',
 '01702',
 '01337',
 '03252',
 '01685',
 '01056',
 '01760',
 '02022',
 '04174',
 '01261',
 '00872',
 '02951',
 '00747',
 '01465',
 '01164',
 '00414',
 '00491',
 '00176',
 '05716',
 '02794',
 '01314',
 '06023',
 '03383',
 '01941',
 '01109',
 '00326',
 '02409',
 '00490',
 '00993',
 '00307',
 '01462',
 '00323',
 '02730',
 '121',
 '02352',
 '01601',
 '02370',
 '02778',
 '01082',
 '00075',
 '02054',
 '02028',
 '01788',
 '02243',
 '03331',
 '01775',
 '05259',
 '01345',
 '06019',
 '00083',
 '00236',
 '01748',
 '01198',
 '02456',
 '02694',
 '01238',
 '02155',
 '00976',
 '01688',
 '00969',
 '02909',
 '05985',
 '04008',
 '02651',
 '00258',
 '05973',
 '00022',
 '02469',
 '00971',
 '01372',
 '02298',
 '00365',
 '0083',
 '01048',
 '01776',
 '00468',
 '00927',
 '01287',
 '02275',
 '02852',
 '02879',
 '05975',
 '01002',
 '00600',
 '01682',
 '02994',
 '08351',
 '05103',
 '05292',
 '05396',
 '05327',
 '00080',
 '01466',
 '04193',
 '02971',
 '02153',
 '00199',
 '00606',
 '02795',
 '00482',
 '00465',
 '00383',
 '04629',
 '00622',
 '00901',
 '02452',
 '03248',
 '00422',
 '01235',
 '02567',
 '04024',
 '09014',
 '1022',
 '00229',
 '04785',
 '01375',
 '00722',
 '02654',
 '04171',
 '00153',
 '00999',
 '01909',
 '02476',
 '00074',
 '02802',
 '03178',
 '03998',
 '05354',
 '02009',
 '01815',
 '02485',
 '56',
 '00581',
 '03044',
 '01147',
 '01387',
 '01785',
 '05967',
 '08903',
 '04777',
 '01264',
 '03511',
 '04073',
 '02379',
 '01018',
 '02854',
 '02882',
 '01773',
 '02305',
 '00392',
 '04012',
 '01820',
 '00641',
 '01603',
 '06016',
 '08939',
 '09023',
 '00027',
 '02271',
 '01383',
 '08995',
 '01857',
 '01879',
 '02507',
 '01891',
 '72483',
 '01882',
 '00259',
 '01460',
 '01995',
 '00613',
 '08979',
 '02783',
 '10999',
 '02396',
 '05831',
 '05197',
 '00589',
 '00733',
 '04019',
 '00017',
 '01152',
 '08968',
 '02248',
 '01435',
 '02132',
 '00943',
 '01182',
 '00471',
 '02224',
 '01942',
 '00162',
 '00689',
 '01062',
 '00591',
 '00688',
 '02170',
 '05147',
 '01428',
 '01326',
 '02175',
 '00929',
 '01834',
 '00401',
 '01589',
 '01630',
 '02496',
 '02389',
 '03411',
 '00780',
 '00639',
 '02514',
 '00082',
 '01065',
 '01450',
 '03035',
 '01177',
 '01293',
 '01402',
 '04127',
 '06724',
 '01735',
 '01819',
 '02144',
 '03410',
 '04118',
 '02049',
 '08944',
 '09002',
 '00242',
 '00009',
 '02072',
 '03326',
 '01031',
 '08254',
 '00374',
 '03909',
 '00387',
 '00555',
 '04187',
 '02692',
 '01965',
 '01743',
 '01329',
 '01598',
 '01201',
 '01932',
 '02480',
 '02727',
 '03273',
 '04652',
 '05806',
 '08314',
 '01252',
 '03068',
 '87720',
 '01736',
 '02045',
 '02272',
 '04046',
 '01427',
 '02459',
 '01166',
 '01203',
 '02188',
 '02510',
 '02687',
 '04094',
 '00882',
 '00169',
 '00598',
 '01188',
 '03612',
 '01090',
 '00545',
 '02679',
 '02755',
 '03950',
 '01552',
 '00869',
 '02979',
 '01447',
 '03231',
 '00338',
 '00936',
 '06000',
 '10975',
 '00691',
 '01591',
 '03487',
 '08942',
 '04115',
 '00403',
 '04693',
 '02016',
 '00520',
 '00597',
 '153',
 '02301',
 '01442',
 '03182',
 '08278',
 '00368',
 '03503',
 '02859',
 '00967',
 '01181',
 '03978',
 '01071',
 '01371',
 '02669',
 '01700',
 '01893',
 '02466',
 '00629',
 '04087',
 '06028',
 '00631',
 '00726',
 '01550',
 '03544',
 '10991',
 '00775',
 '03335',
 '01007',
 '02204',
 '03121',
 '00654',
 '06030',
 '01004',
 '01086',
 '01810',
 '05281',
 '04168',
 '02154',
 '983',
 '02297',
 '00944',
 '08532',
 '01885',
 '00624',
 '02348',
 '03359',
 '219',
 '09021',
 '00708',
 '04717',
 '01911',
 '00761',
 '01964',
 '01855',
 '03378',
 '04116',
 '01331',
 '01113',
 '01833',
 '52',
 '03261',
 '01106',
 '01204',
 '01298',
 '00851',
 '01900',
 '01206',
 '02781',
 '03128',
 '01977',
 '00576',
 '01543',
 '03287',
 '48',
 '01099',
 '02351',
 '05302',
 '03565',
 '00773',
 '02965',
 '05111',
 '06058',
 '03224',
 '05107',
 '00658',
 '02858',
 '00756',
 '02215',
 '00905',
 '01849',
 '03399',
 '03324',
 '01284',
 '02648',
 '01265',
 '06012',
 '01537',
 '09041',
 '03438',
 '02137',
 '02096',
 '01708',
 '01816',
 '05227',
 '00565',
 '01343',
 '01517',
 '02061',
 '00919',
 '00539',
 '02866',
 '00373',
 '04664',
 '00908',
 '00671',
 '03327',
 '01697',
 '04658',
 '00285',
 '03039',
 '04090',
 '01379',
 '03267',
 '08909',
 '01888',
 '04030',
 '00670',
 '02871',
 '02218',
 '01095',
 '03405',
 '15069',
 '03207',
 '02931',
 '01141',
 '01011',
 '01010',
 '03064',
 '05146',
 '01040',
 '01360',
 '00079',
 '01514',
 '01242',
 '00802',
 '02779',
 '01597',
 '04735',
 '03104',
 '01300',
 '01212',
 '09012',
 '04754',
 '09006',
 '00286',
 '03269',
 '01952',
 '00334',
 '03553',
 '00777',
 '02069',
 '05100',
 '08957',
 '01079',
 '00170',
 '05219',
 '03546',
 '01497',
 '01114',
 '01363',
 '02844',
 '00519',
 '10992',
 '01740',
 '00502',
 '01918',
 '02973',
 '04622',
 '01223',
 '03033',
 '01756',
 '03061',
 '01288',
 '196',
 '01404',
 '01341',
 '04191',
 '06262',
 '10962',
 '08596',
 '02468',
 '02214',
 '02919',
 '00930',
 '01914',
 '00956',
 '01123',
 '02367',
 '04661',
 '03238',
 '01185',
 '03997',
 '00949',
 '05232',
 '02000',
 '03220',
 '05984',
 '05350',
 '00669',
 '01579',
 '02286',
 '02532',
 '00274',
 '01828',
 '02666',
 '01907',
 '01054',
 '02624',
 '00015',
 '09016',
 '00610',
 '107',
 '02199',
 '02934',
 '00942',
 '05116',
 '01157',
 '00261',
 '00103',
 '00000',
 '05957',
 '04640',
 '00345',
 '01733',
 '04813',
 '00312',
 '01021',
 '02010',
 '02822',
 '05965',
 '02202',
 '00302',
 '01453',
 '03309',
 '08996',
 '02244',
 '03548',
 '00692',
 '00342',
 '03123',
 '00010',
 '02232',
 '01439',
 '06004',
 '44147',
 '01463',
 '180',
 '05114',
 '00310',
 '00268',
 '02084',
 '01097',
 '02041',
 '01146',
 '02201',
 '04753',
 '00911',
 '01557',
 '06053',
 '00462',
 '00442',
 '00317',
 '02710',
 '02790',
 '10972',
 '00897',
 '01333',
 '10971',
 '00686',
 '02945',
 '05997',
 '03059',
 '00975',
 '08477',
 '01584',
 '01479',
 '03425',
 '04674',
 '00134',
 '00685',
 '00399',
 '00149',
 '01976',
 '00992',
 '01192',
 '00503',
 '03218',
 '03106',
 '04695',
 '01309',
 '01396',
 '02672',
 '00847',
 '02147',
 '02643',
 '01253',
 '02756',
 '03304',
 '0018',
 '00548',
 '00711',
 '00429',
 '01526',
 '01273',
 '00533',
 '03137',
 '04043',
 '01134',
 '00535',
 '06008',
 '09000',
 '00067',
 '02978',
 '00635',
 '01229',
 '01349',
 '03711',
 '05223',
 '05095',
 '08960',
 '00060',
 '04673',
 '03361',
 '04793',
 '02073',
 '01545',
 '01718',
 '05976',
 '01575',
 '11111',
 '01405',
 '02019',
 '04253',
 '00506',
 '02741',
 '05097',
 '01231',
 '00837',
 '04660',
 '02819',
 '05228',
 '04637',
 '00139',
 '02594',
 '00257',
 '01884',
 '00480',
 '03179',
 '00048',
 '00536',
 '01234',
 '00900',
 '04974',
 '00112',
 '00366',
 '03373',
 '00783',
 '04811',
 '05118',
 '02892',
 '01281',
 '00745',
 '02399',
 '00729',
 '01165',
 '03132',
 '02664',
 '03299',
 '09042',
 '03225',
 '02320',
 '00195',
 '01790',
 '02839',
 '04694',
 '05996',
 '01392',
 '02599',
 '01560',
 '01533',
 '02404',
 '00435',
 '08991',
 '01342',
 '05382',
 '00633',
 '00167',
 '02151',
 '00797',
 '03593',
 '00712',
 '00255',
 '00653',
 '01096',
 '01732',
 '04682',
 '01567',
 '10968',
 '00646',
 '02953',
 '10981',
 '01818',
 '01548',
 '02750',
 ...}

In [ ]:
drop_data = drop_data[(drop_data['PartitionKey'].astype(str).str.isdigit()) & (drop_data['PartitionKey'].str.len() == 5)] # เช็ค type ของข้อมูลโดยใช้ str.isdigit() และทำการเลือกข้อมูลที่เป็นตัวเลข 5 หลักเท่านั้น
drop_data

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon
4,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,00000,13777,โรงพยาบาลศรีนครินทร์ มหาวิทยาลัยขอนแก่น,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,1.0,เมืองขอนแก่น,1.0,ในเมือง
5,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14:46:08,ปกติ (เหลืองใส),4,00001,06307,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านเกาะ ตำบลบ้านดารา,2.0,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,7.0,พิชัย,2.0,บ้านดารา
6,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15:27:45,ปกติ (เหลืองใส),4,00001,05328,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านโคกประสิทธิ์,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,18.0,ฆ้องชัย,3.0,โคกสะอาด
7,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,"iPhone13,4",06302,10:16:46,ปกติ (เหลืองใส),3,00001,06302,โรงพยาบาลส่งเสริมสุขภาพตำบลสองห้อง,2.0,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,5.0,ฟากท่า,4.0,สองห้อง
8,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,"iPhone9,4",05059,12:26:38,ปกติ (เหลืองใส),3,00001,05059,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านดอนดู่,7.0,สาขาพื้นที่(ขอนแก่น),44.0,มหาสารคาม,10.0,นาดูน,6.0,หัวดง
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38335,68768,B7F36631-D2C4-4EB5-852D-790BFAFDFD71,2022-03-24,"iPhone11,8",11088,10:30:22,ปกติ (เหลืองใส),2,89170,11088,โรงพยาบาลห้วยผึ้ง,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง
38336,68768,899A7591-50C9-40BC-9746-A831A08DE980,2022-03-24,"iPhone11,8",11088,10:29:37,ปกติ (เหลืองใส),0,90470,11088,โรงพยาบาลห้วยผึ้ง,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง
38337,68768,BF39F27C-1B43-4C97-A034-D7A579BED2B6,2022-03-24,"iPhone11,8",11088,10:24:40,ปกติ (เหลืองใส),1,91123,11088,โรงพยาบาลห้วยผึ้ง,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง
38341,68768,D8A3A9EA-929E-4CEB-BFDF-C9BE093EA663,2022-03-24,"iPhone11,8",11088,10:25:32,ปกติ (เหลืองใส),1,99444,11088,โรงพยาบาลห้วยผึ้ง,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง
38342,99771,E04D3D60-B916-40A1-AE77-91CCD89DD084,2022-03-31,"iPhone10,5",05396,11:03:40,ปกติ (เหลืองใส),0,99771,05396,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านสูงเนิน,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,10.0,คำม่วง,9.0,เนินยาง

In [ ]:
drop_data.isnull().any() # เช็คค่า missing

user            False
RowKey          False
date            False
phone           False
site            False
time            False
urine           False
ov              False
PartitionKey    False
hcode           False
name            False
zone_code       False
zone_name       False
provincecode    False
province        False
amphurcode      False
amphur          False
tamboncode      False
tambon          False
dtype: bool

In [ ]:
drop_data

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon
4,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,00000,13777,โรงพยาบาลศรีนครินทร์ มหาวิทยาลัยขอนแก่น,7.0,สาขาพื้นที่(ขอนแก่น),40.0,ขอนแก่น,1.0,เมืองขอนแก่น,1.0,ในเมือง
5,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14:46:08,ปกติ (เหลืองใส),4,00001,06307,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านเกาะ ตำบลบ้านดารา,2.0,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,7.0,พิชัย,2.0,บ้านดารา
6,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15:27:45,ปกติ (เหลืองใส),4,00001,05328,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านโคกประสิทธิ์,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,18.0,ฆ้องชัย,3.0,โคกสะอาด
7,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,"iPhone13,4",06302,10:16:46,ปกติ (เหลืองใส),3,00001,06302,โรงพยาบาลส่งเสริมสุขภาพตำบลสองห้อง,2.0,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,5.0,ฟากท่า,4.0,สองห้อง
8,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,"iPhone9,4",05059,12:26:38,ปกติ (เหลืองใส),3,00001,05059,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านดอนดู่,7.0,สาขาพื้นที่(ขอนแก่น),44.0,มหาสารคาม,10.0,นาดูน,6.0,หัวดง
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38335,68768,B7F36631-D2C4-4EB5-852D-790BFAFDFD71,2022-03-24,"iPhone11,8",11088,10:30:22,ปกติ (เหลืองใส),2,89170,11088,โรงพยาบาลห้วยผึ้ง,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง
38336,68768,899A7591-50C9-40BC-9746-A831A08DE980,2022-03-24,"iPhone11,8",11088,10:29:37,ปกติ (เหลืองใส),0,90470,11088,โรงพยาบาลห้วยผึ้ง,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง
38337,68768,BF39F27C-1B43-4C97-A034-D7A579BED2B6,2022-03-24,"iPhone11,8",11088,10:24:40,ปกติ (เหลืองใส),1,91123,11088,โรงพยาบาลห้วยผึ้ง,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง
38341,68768,D8A3A9EA-929E-4CEB-BFDF-C9BE093EA663,2022-03-24,"iPhone11,8",11088,10:25:32,ปกติ (เหลืองใส),1,99444,11088,โรงพยาบาลห้วยผึ้ง,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง
38342,99771,E04D3D60-B916-40A1-AE77-91CCD89DD084,2022-03-31,"iPhone10,5",05396,11:03:40,ปกติ (เหลืองใส),0,99771,05396,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านสูงเนิน,7.0,สาขาพื้นที่(ขอนแก่น),46.0,กาฬสินธุ์,10.0,คำม่วง,9.0,เนินยาง

# Save File

In [ ]:
drop_data.to_csv('drop_data.csv', encoding='utf-8')